// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4t3I1p6woOob0LvHQsrsMYhV8Q4baIrs',
    appId: '1:249367131069:web:97f6ed7aad29d79febd8d4',
    messagingSenderId: '249367131069',
    projectId: 'hackathon-766ae',
    authDomain: 'hackathon-766ae.firebaseapp.com',
    storageBucket: 'hackathon-766ae.appspot.com',
    measurementId: 'G-GQ0MR4GKGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs0Mw8-juZKTCOadpVBVjsQrD7Fsfm1Xs',
    appId: '1:249367131069:android:eb791df2a025103bebd8d4',
    messagingSenderId: '249367131069',
    projectId: 'hackathon-766ae',
    storageBucket: 'hackathon-766ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAglTXdhYEIQiJ2pG45Lm_nSw1xonL7I_0',
    appId: '1:249367131069:ios:3dc48197df1bbb17ebd8d4',
    messagingSenderId: '249367131069',
    projectId: 'hackathon-766ae',
    storageBucket: 'hackathon-766ae.appspot.com',
    iosClientId: '249367131069-s0vl7h0r0ts9odpnesqqmgn3nitavuou.apps.googleusercontent.com',
    iosBundleId: 'com.example.task',
  );
}
